version: "3"

networks:
  webapp:

services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
      - db
    networks:
      - webapp

  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=my_test_server
    networks:
      - webapp

  db:
    container_name:  ${APP_NAME}_mysql
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:  ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - webapp

  adminer:
    container_name:  ${APP_NAME}_adminer
    image: adminer
    restart: always
    ports:
      - "8100:8080"
    networks:
      - webapp

volumes:
  mysql-data:
